version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - HUGGINGFACE_API_KEY=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
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: always
